services:
  api:
    build:
      context: .
      dockerfile: ./iris/Dockerfile
    platform: linux/x86_64
    ports:
      - "8080:8080"
    depends_on:
     - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/iris
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=toor
      - SPRING_JWT_SECRET_KEY=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - REDIS_HOST=redis
      - RAYGAN_SMS_SENDER_NUMBER=null
      - RAYGAN_SMS_USERNAME=null
      - RAYGAN_SMS_PASSWORD=null
    restart: unless-stopped
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=iris'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=toor'
    ports:
      - '5432'
    restart: unless-stopped
  redis:
    image: 'redis/redis-stack:latest'
    ports:
      - "6379:6379"
      - "8001:8001"
    restart: unless-stopped