services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      elastic:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/iris
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=toor
      - SPRING_JWT_SECRET_KEY=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - RAYGAN_SMS_SENDER_NUMBER=50002200888861
      - RAYGAN_SMS_USERNAME=sadegh369
      - RAYGAN_SMS_PASSWORD=12345678Codestars
      - ELASTIC_HOST=elastic
      - RESOURCE_PATH=resources
    restart: unless-stopped
    volumes:
      - 'app_files:/app/files'
      - 'app_logs:/app/logs'
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=iris'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=toor'
    ports:
      - '5433:5432'
    restart: unless-stopped
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
  elastic:
    image: elasticsearch:7.17.9
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - "9200:9200"
    restart: unless-stopped
    volumes:
      - "elastic_data:/usr/share/elasticsearch/data"
    healthcheck:
      test: [ "CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1" ]
      interval: 30s
      timeout: 30s
      retries: 3
volumes:
  postgres_data:
  app_files:
  app_logs:
  elastic_data: