services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
      - elastic
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/iris
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=toor
      - SPRING_JWT_SECRET_KEY=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      - RAYGAN_SMS_SENDER_NUMBER=null
      - RAYGAN_SMS_USERNAME=null
      - RAYGAN_SMS_PASSWORD=null
    restart: unless-stopped
    volumes:
      - 'app_files:/app/files'
      - 'app_logs:/app/logs'
  db:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=iris'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=toor'
    ports:
      - '5432'
    restart: unless-stopped
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  elastic:
    image: elasticsearch:7.17.9
    environment:
      - 'discovery.type=single-node'
      - 'xpack.security.enabled=false'
    ports:
      - "9200:9200"
    restart: unless-stopped
    volumes:
      - "elastic_data:/usr/share/elasticsearch/data"

volumes:
  postgres_data:
  app_files:
  app_logs:
  elastic_data: